name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Connexion à GitHub Packages (GHCR)
      - name: Connexion a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3 & 4. Build et Push de l'image Docker
      - name: Build et Push de l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
